services:
  api:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/backend
    command: bash -c "python manage.py runserver 0.0.0.0:3000"

  web:
    build: ./frontend
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/frontend
