# Generated by Django 4.2.2 on 2023-06-21 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_challenge', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entries',
            new_name='Entry',
        ),
    ]
