# Generated by Django 4.2.2 on 2023-06-22 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_challenge', '0003_rename_title_entry_name_remove_entry_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='dev_name2',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='dev_name3',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='dev_name4',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='dev_name5',
        ),
        migrations.AlterField(
            model_name='entry',
            name='dev_name1',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
