# Generated by Django 4.2.2 on 2023-06-22 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_challenge', '0004_remove_entry_dev_name2_remove_entry_dev_name3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='dev_name1',
            new_name='dev_names',
        ),
    ]
