# Generated by Django 4.2.2 on 2023-06-24 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_challenge', '0005_rename_dev_name1_entry_dev_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='dev_names',
            new_name='dev_name1',
        ),
        migrations.AddField(
            model_name='entry',
            name='dev_name2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='dev_name3',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='dev_name4',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='dev_name5',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='methodology',
            field=models.CharField(default='Agile', max_length=120),
        ),
    ]
